name: konwerter.exe
on:
  schedule:
    - cron: "0 0 * * 0"  
  push:
    branches:
      - master  
  workflow_dispatch:  

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Zainstalowanie potrzebnych zależności

      - name: Build .exe
        run: |
          python build.py  # Polecenie do budowania pliku .exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyApp  
          path: \main.exe\main.exe
